### ISSUE TITLE
ReplayGain settings are ignored sometimes when switching between different playlists.

### ISSUE THREAD

**Issue by Alexey104** [fooyin/fooyin#402]
**Describe the bug**
Sometimes, when switching between different playlists, `ReplayGain` settings do not apply to the tracks in a playlist until playback is stopped and restarted. I use the following `ReplayGain` settings:
`mode: Apply gain and prevent clipping`
`type: Use track-based gain`

**To Reproduce**
1) Add some tracks to a playlist and play them. Everything is fine at this point, `ReplayGain` tags are respected.
2) Use library filter to find a certain album and click on that album. A new playlist named "Filter Result" will be created with the content of the selected album. Start playing this playlist - everything is good, `ReplayGain` tags are respected.
3) Stop the playback and switch to the previous playlist from step 1. Start playback - the tracks are suddenly very loud and toggling `ReplayGain` settings ON/OFF does not affect the volume at all, the settings are just ignored.
4) Stop and restart the playback - now the volume is much quieter, `ReplayGain` settings are applied after STOP/PLAY.

**Expected behaviour**
`ReplayGain` settings should always apply to all tracks in all playlists.

**System:**
 - OS: ArchLinux
 - fooyin version: 0.8.1 (AUR)

**Comment by Alexey104** [comment]
Thank you for the response!

> Are you using the `fooyin` package or the `fooyin-git` package?

I've tried both and can reproduce this in either package.

**Comment by Alexey104** [comment]
I think it's worth noting that it also happens if I just drag a relatively big music folder (500GB+) from the directory tree to the playlist and hit play immediately after tracks have been displayed in the playlist. The playback is very loud, RG settings qre not respected and just switching tracks doesn't solve the problem. Only after I hit "stop" and "play" again does the volume level adjusted according to RG tags. I play my music from a slow spinning disk. Not sure, maybe there's some race conditions/timing issues causing the playback to start before RG tags has been read from files? I don't have this problem in other players. Not sure if it does matter, but I use [rsgain](https://github.com/complexlogic/rsgain) for calculating and writing RG tags.

**Comment by Alexey104** [comment]
OK, after listening to some music with fooyin I found out that the issue actually has nothing to do with switching between playlists. It is reproducible by just switching tracks withing the same playlist.

Assume, there are two tracks `A` and `B` with the following RG values:
```
// Track A (classic record, pretty quiet)
REPLAYGAIN_ALBUM_GAIN=-2.05 dB
REPLAYGAIN_ALBUM_PEAK=0.999969
REPLAYGAIN_TRACK_GAIN=-1.39 dB
REPLAYGAIN_TRACK_PEAK=0.860443

// Track B (modern, very loud mastering)
REPLAYGAIN_ALBUM_GAIN=-11.10 dB
REPLAYGAIN_ALBUM_PEAK=1
REPLAYGAIN_TRACK_GAIN=-11.33 dB
REPLAYGAIN_TRACK_PEAK=1
```

If `Track A` plays after `Track B`, then it is way too quiet. Toggling STOP/PLAY makes it sound at the same perceived level as `Track B`. And vice-versa - if `Track B` plays after `Track A`, then it is suddenly extremely loud like as ReplayGain is disabled. Toggling STOP/PLAY makes it sound at the same perceived level as `Track A`. So, to play all tracks at the same perceived level I have to toggle STOP/PLAY after every track, which is weird. Not sure, maybe this is related to my audio interface (it's an external USB card), but no such behavior in MPD or Deadbeef with RG on.

**Comment by ludouzi** [comment]
Thanks for all the testing! That massively helps in narrowing down the issue.

If gapless playback is enabled, subsequent tracks of the same format don't cause a reload of the audio renderer, which is probably where the issue lies. I'll have this fixed in a bit.

**Comment by Alexey104** [comment]
I’ve just upgraded to the latest Git version, and I can no longer reproduce the issue. Thank you so much—I truly appreciate your efforts! You've done an outstanding job on Fooyin!

**Comment by unhappy-ending** [comment]
I'm actually having this exact problem using version 0.8.1. I have a very loud modern album using album gain and a quiet older album using album gain. One is -1 db, the other -11. When switching between the two RG is ignored. If I go and disable gapless playback, and switch between the two, it's instantly noticeably even.

I don't even have to switch between the two. I can use the modern album, turn on gapless, and it's louder. I can stop playback, disable gapless again, and then the album is quiet.

What info do you need in order to reproduce?

**Comment by Dama624** [comment]
Can confirm the issue still persists in 0.8.1

Volume appears to inherit previous song's ReplayGain metadata, need to Stop and replay the song to adjust volume again.

Gapless Playback is **enabled**; the issue does seem to go away when Gapless Playback is disabled.
